config/routes.rb
Rails.application.routes.draw do
  get 'game_results/index'
  root "articles#index"

  delete '/articles', to: 'articles#destroy_all', as: 'delete_all_articles'

  resources :articles

  post 'game_results', to: 'articles#game_results'
  get 'game_results', to: 'articles#game_results'

  get 'manage_articles', to: 'articles#manage_articles'
  
  delete '/articles/:id', to: 'articles#destroy', as: 'delete_article'

  get 'about', to: 'articles#about'

  get 'testindex', to: 'articles#testindex'

  get 'ballparks', to: 'ballparks#index', as: 'ballparks'

  devise_for :users


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 5 }
    
  end
  

app/models/user.rb
class User < ApplicationRecord
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :validatable
    
    # Define the authentication attribute as email
    devise :database_authenticatable, authentication_keys: [:email]
  
    # Add any additional configurations, such as password complexity rules
    validates :password, presence: true, length: { minimum: 6 }, if: -> { new_record? || changes[:password] }
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
  
    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end
  end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy, :game_results, :destroy_all]
  
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to game_results_path
  end
  
  
  def destroy_all
    Article.destroy_all
    redirect_to root_path, notice: 'All articles have been deleted!'
  end

  def game_results
    @articles = Article.all
  end


  private
    def article_params
      params.require(:article).permit(:title, :body, :image_url)
    end
end

app/controllers/ballparks_controller.rb
require 'open-uri'
require 'nokogiri'

class BallparksController < ApplicationController
  def index
    @ballparks = []
    html = URI.open('https://baseballparks.com/ballparkchart/').read
    doc = Nokogiri::HTML(html)

    doc.css('table').last.css('tr').each do |row|
      cols = row.css('td').map(&:text)
      next if cols.empty?

      franchise, league, stadium, city, architect, first_year, last_year, capacity, lf, lcf, cf, rcf, rf, _, _, _, fair_territory, _ = cols

      @ballparks << { 
        franchise: franchise,
        league: league,
        stadium: stadium,
        city: city,
        architect: architect,
        first_year: first_year.to_i,
        last_year: last_year.to_i,
        capacity: capacity.to_i,
        left_field: lf.to_f,
        left_center: lcf.to_f,
        center_field: cf.to_f,
        right_center: rcf.to_f,
        right_field: rf.to_f,
        fair_territory: fair_territory ? fair_territory.gsub(/,/, '').to_f : nil

      }
    end
  end
end

app/controllers/game_results_controller.rb
class GameResultsController < ApplicationController
  def index
        # Enqueue the background job to run
        UpdateGameResultsJob.schedule

        # Load the articles to display
        @articles = Article.all
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    def new(*args)
      respond_to do |format|
        format.html { super(*args) }
        format.json { render json: { message: 'success' } }
      end
    end
  end
  

app/controllers/sessions_controller.rb
class User::SessionsController < Devise::SessionsController
end

app/controllers/users_controller.rb
class User < ApplicationRecord
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :validatable
  
    # Define the authentication attribute as email
    devise :database_authenticatable, authentication_keys: [:email]
  
    # Add any additional configurations, such as password complexity rules
    validates :password, presence: true, length: { minimum: 6 }, if: -> { new_record? || changes[:password] }
  
    # Associations with other models
    has_many :posts
    has_many :comments
  
    # Custom instance methods
    def full_name
      "#{first_name} #{last_name}"
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/ballparks_helper.rb
module BallparksHelper
end

app/helpers/game_results_helper.rb
module GameResultsHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :image_url %><br>
    <%= form.text_field :image_url %>
    <% article.errors.full_messages_for(:image_url).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/about.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>About This Blog</title>
    <%= stylesheet_link_tag 'index' %>
  </head>
  <body>
    <header>
      <nav>
        <div class="logo">
          <%= image_tag 'mlb.png', alt: 'My Blog Logo' %>
        </div>
        <ul class="nav-links">
          <li><%= link_to 'Home', root_path %></li>
          <li class="title"> MLB Blog</li>
        </ul>
      </nav>
    </header>
    <div class="container">
      <h1>About This Blog (this was written by AI)</h1>

      <p>Welcome to MLB Scores Blog, a blog dedicated to recording the final scores of MLB games. Here you can find the latest scores of your favorite baseball teams and stay up-to-date with the latest happenings in the world of baseball.</p>

      <p>The team of dedicated writers and researchers work hard to bring you the most accurate and reliable scores from all around the league. We strive to provide the most comprehensive coverage of MLB games and make it easy for you to stay informed.</p>

      <p>Thank you for choosing MLB Scores Blog as your go-to source for the latest MLB scores. Be sure to check back often for the latest updates and news from around the league.</p>

      <p><%= link_to "Back to Home", root_path, class:"dark-theme" %></p>
    </div>
  </body>
</html>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

app/views/articles/game_results.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Game Results | 2023 MLB Season</title>
    <%= stylesheet_link_tag 'game_results' %>
  </head>
  <body>
    <header>
      <nav>
        <div class="logo">
          <%= image_tag 'mlb.png', alt: 'My Blog Logo' %>
        </div>
        <ul class="nav-links">
          <li><%= link_to 'Home', root_path %></li>
          <li class="title"> MLB Blog</li>
        </ul>
      </nav>
    </header>
    <div class="container">
      <h2> 2023 MLB Season - Game Results </h2>

      <ul class="list-unstyled">
        <% @articles.each do |article| %>
          <li>
            <%= link_to article.title, article, class: "dark-theme"%>
            </a>
          </li>
        <% end %>
      </ul>

      <h2> End of Games </h2>

      <h3><%= link_to "Back to Home", root_path, class: "dark-theme" %></h3>
    </div>
  </body>
</html>

app/views/articles/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Blog Homepage</title>
    <%= stylesheet_link_tag 'index' %>
  </head>
  <body>
    <header>
      <nav>
        <div class="logo">
          <%= image_tag 'mlb.png', alt: 'My Blog Logo' %>
        </div>
        <ul class="nav-links">
          <li><%= link_to 'Home', root_path %></li>
          <li class="title"> MLB Blog</li>
        </ul>
      </nav>
    </header>
    <section class="hero">
        <div class="hero-text">
            <h1>MLB Blog</h1>
            <p>Source for up to date information on the 2023 MLB season</p>
        </div>
        <div class="card">
            <%= link_to game_results_path do %>
                <h2>Game Results</h2>
                <p>Check out the latest game results!</p>
            <% end %>
        </div>  
    </section>
    <section class="cards">
        <div class="card">
            <%= link_to game_results_path do %>
                <h2>Game Results</h2>
                <p>Results of every game played so far this season. Sorted by date</p>
            <% end %>
        </div>
        <div class="card">
            <%= link_to about_path do %>
                <h2>About this Blog</h2>
                <p>Link to about path</p>
            <% end %>
        </div>
        <div class="card">
            <%= link_to manage_articles_path do %>
                <h2>Manage Articles</h2>
                <p>Link to manage articles</p>
            <% end %>
        
        </div>
        <div class="card">
          <%= link_to ballparks_path do %>
            <h2>MLB Ballparks</h2>
            <p>Information about each MLB ballpark</p>
          <% end %>
        </div>
      </section>
  </body>
</html>

app/views/articles/manage_articles.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Blog Homepage</title>
    <%= stylesheet_link_tag 'index' %>
  </head>
  <body>
    <header>
      <nav>
        <div class="logo">
          <%= image_tag 'mlb.png', alt: 'My Blog Logo' %>
        </div>
        <ul class="nav-links">
          <li><%= link_to 'Home', root_path %></li>
          <li class="title"> MLB Blog</li>
        </ul>
      </nav>
    </header>
    <div class="dark-theme">
      <h1>Manage Articles </h1>
      <h4><%= button_to 'Delete All Articles', articles_path, method: :delete, class: 'btn btn-danger delete-all-button', data: { confirm: 'Are you sure?' } %>
      </h4>
      <h3><%= link_to "Create New Article Here", new_article_path, class: "dark-theme" %></h3>
      <%= link_to "Back to Home", root_path, class: "dark-theme" %>
    </div>
  </body>
</html>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= form_with model: @article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% @article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% @article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p><%= @article.body %></p>

<%= image_tag @article.image_url, class: "article-image-show" %>




<p><%= link_to "Edit Article", edit_article_path(@article) %></p>

<%= button_to "Delete Article", delete_article_path(id: @article.id), method: :delete, data: { confirm: "Are you sure?" } %>






<%= link_to "Go Back To Home Page", root_path%>

app/views/ballparks/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>All US Ballparks</title>
    <%= stylesheet_link_tag 'ballparks' %>
  </head>
  <body>
    <h1>Ballparks</h1>
    <%= image_tag 'mlb.png', alt: 'My Blog Logo', class: 'ballpark_logo' %>
    <table>
      <thead>
        <tr>
          <th>Franchise</th>
          <th>League</th>
          <th>Stadium</th>
          <th>City</th>
          <th>Architect</th>
          <th>First Year</th>
          <th>Last Year</th>
          <th>Capacity</th>
          <th>Left Field</th>
          <th>Left Center</th>
          <th>Center Field</th>
          <th>Right Center</th>
          <th>Right Field</th>
          <th>Fair Territory (sq ft)</th>
        </tr>
      </thead>
      <tbody>
        <% @ballparks.each do |ballpark| %>
          <tr>
            <td><%= ballpark[:franchise] %></td>
            <td><%= ballpark[:league] %></td>
            <td><%= ballpark[:stadium] %></td>
            <td><%= ballpark[:city] %></td>
            <td><%= ballpark[:architect] %></td>
            <td><%= ballpark[:first_year] %></td>
            <td><%= ballpark[:last_year] %></td>
            <td><%= ballpark[:capacity] %></td>
            <td><%= ballpark[:left_field] %></td>
            <td><%= ballpark[:left_center] %></td>
            <td><%= ballpark[:center_field] %></td>
            <td><%= ballpark[:right_center] %></td>
            <td><%= ballpark[:right_field] %></td>
            <td><%= ballpark[:fair_territory] %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </body>
</html>

app/views/game_results/index.html.erb
<h1>GameResults#index</h1>
<p>Find me in app/views/game_results/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MLB Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="dark-theme">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: "flash #{name}" %>
    <% end %>
    
    <%= yield %>
  </body>
</html>